name: CI

on:
  push:
    branches:
    - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.x
    - name: Test
      run: make test
    - name: Lint
      run: make lint
      if: matrix.os != 'windows-latest'
    - name: Get metadata
      run: sh -c "MACKEREL_AGENT_PLUGIN_META=1 ./mackerel-plugin-battery"
    - name: Get metrics
      run: sh -c "./mackerel-plugin-battery || :"
